sudo: required
services:
    - docker
before_install:
    - docker build -t 33142308/fibonnaci-calc -f ./client/Dockerfile.dev ./client

script:
    - docker run 33142308/fibonnaci-calc npm test -- --coverage

after_success:
    - docker build -t 3142308/fibonnaci-client ./client 
    - docker build -t 3142308/fibonnaci-nginx ./nginx 
    - docker build -t 3142308/fibonnaci-server ./server 
    - docker build -t 3142308/fibonnaci-worker ./worker

    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

    - docker push 33142308/fibonnaci-client:latest
    - docker push 33142308/fibonnaci-nginx:latest
    - docker push 33142308/fibonnaci-server:latest
    - docker push 33142308/fibonnaci-worker:latest




